# Generated by Django 5.0.6 on 2024-07-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="zipcode",
            field=models.CharField(blank=True, default=False, max_length=20),
        ),
    ]
