# Generated by Django 5.0.6 on 2024-07-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_userprofile_zipcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="zipcode",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
